### ISSUE TITLE
при установке выдает ошибку ERROR: relation "tables_fields" does not exist LINE 1: insert into tables_fields ("name","title","category","data_s... ^ install/installController.php(0) common/Controller.php(134) common/Controller.php(148)

### ISSUE THREAD

**Issue by eugenechertikhin** [totumonline/totum-mit#165]
ERROR: relation "tables_fields" does not exist LINE 1: insert into tables_fields ("name","title","category","data_s... ^ install/installController.php(0) common/Controller.php(134) common/Controller.php(148)

php 7.3
pgsql 9.5
os oraclelinux 7.8

**Comment by poluninatm** [comment]
Спасибо! Была проблема в установщике - с путями к утилитам PostgreSql, отличными от умолчальных, мы его не тестировали. Поправила установку путей в конфиг, а также теперь при ошибке заливки первичной sql, отдает ошибку ssh в том числе.
