### ISSUE TITLE
При установке на NetAngels ошибка

### ISSUE THREAD

**Issue by infraymer** [totumonline/totum-mit#202]
<img width="1440" alt="Снимок экрана 2020-12-27 в 13 09 29" src="https://user-images.githubusercontent.com/18283035/103166598-866a7880-4845-11eb-93eb-cc789399c29d.png">

**Comment by olegenii** [comment]
Аналогичная ошибка

**Comment by ttm-alexeypolunin** [comment]
Да, не обновили документацию по установке. Сейчас исправлено https://docs.totum.online/ustanovka, видеоинструкция тоже обновлена.
