### ISSUE TITLE
Change lang to EN from ru

### ISSUE THREAD

**Issue by dwtcourses** [totumonline/totum-mit#203]
Hi,
I want to add English as a language interface can you let me know, if its already in pipeline or how can i change Russian to English (lang="ru") parameter

Regards,
Shiv

**Comment by ttm-alexeypolunin** [comment]
added in pipe
estimate in 2-3 months

**Comment by dwtcourses** [comment]
thank you for your response, appreciate it.

**Comment by dwtcourses** [comment]
Team,
please let me know any updates on this issue

**Comment by poluninatm** [comment]
We've already translated the documentation -it's on review- and we're starting to work on the internationalization part.

**Comment by poluninatm** [comment]
It will be released with a big update with the php8 migration. Process in branch devphp8s

**Comment by dwtcourses** [comment]
Fantastic... thank you for your update
