### ISSUE TITLE
Расчетная в цикле

### ISSUE THREAD

**Issue by i4j5** [totumonline/totum-mit#205]
При создании таблицы Расчетная в цикле отредактировать или удалить ее не получается. Пишет Неверный путь к таблице. Воспользуйтесь деревом

**Comment by ttm-alexeypolunin** [comment]
Расчетная в цикле не может существовать без таблицы Циклов. Скорее всего при создании вы не изменили ее положение в дереве. Для Расчетных в цикле корнем должна быть выбрана одна из таблиц Циклов.

Пойдите Системные таблицы — Основные — Таблицы и поля — Список таблиц -- найдите созданную таблицу и в поле Положение в дереве выберите таблицу циклов.

**Comment by i4j5** [comment]
Ок!
