### ISSUE TITLE
selectlist 

### ISSUE THREAD

**Issue by i4j5** [totumonline/totum-mit#206]
= : SelectListAssoc(table: 'users';  field: 'fio';  where:  'roles' = 23;) - Получаем пользователей где id роли 23 
Как выбрать пользователей с у которых id роли 23 или 1?

**Comment by ttm-alexeypolunin** [comment]
=: selectRowListForSelect(table: 'users'; field: 'fio'; where: 'roles' = $list)

list: listCreate(item: 1; item: 23)

или

=: selectRowListForSelect(table: 'users'; field: 'fio'; where: 'roles' = json`[1,23]`)


по эксплуатации пишите вопросы в телеграм на @alexeypolunin сайт вопрос-ответ будет чуть позже
