### ISSUE TITLE
Дополнение документации

### ISSUE THREAD

**Issue by mervick** [totumonline/totum-mit#207]
Здравствуйте.
Добавьте пожалуйста больше информации в документации по использованию параметра `previewscode` функции [selectRowListForSelect](https://docs.totum.online/functions#fn-selectRowListForSelect).  
Насколько я понимаю параметр принимает некий код, однако не ясно какой.

**Comment by ttm-alexeypolunin** [comment]
Это прародитель panel...-функций по принципу работы и параметра `code` в функциях типа linkToInput

https://docs.totum.online/specific-codes#panel-format

они в `code` ожидают код как строку:

```
...; code: $code; ...

code: "=: linkToDataText(title: '...'; text: '...')"
```

или `name` поля в текущей таблице, что бы взять код-действия оттуда

`previewscode` сейчас не может взять код по name и по своей сути очень похож на panelHtml:

вот подход как накидать код в виде строки прямо в текущем коде:

```
= : selectRowListForSelect(table: 'pokupateli'; field: 'imya__telefon'; order: 'fio' asc; previewscode: $code)

code: str` $s1 + $#nl + $s2` 

	s1: "=: listCreate(item: $rowCreate)"
	s2: "rowCreate: rowCreate(field: 'title' = 'Тест'; field: 'value' = 'Значение')"

```

или можно сделать где-нибудь поле типа текст, туда написать код и взять этот код `@table.field`

`name` — есть сейчас в доках, это для форм, для чего он там мы не помним, разберемся, в основном интерфейсе работает без него

`previewscode` получает переменную $#val в которую кладется основание селекта (те можно вычислить превью кодом)

экстра-редко это все используется, мне кажется мы только один раз применяли в реальном проекте — проще через `panelHtml` вывести доп-инфу

**Comment by mervick** [comment]
Спасибо
