### ISSUE TITLE
Оптимизация notifications?

### ISSUE THREAD

**Issue by mervick** [totumonline/totum-mit#208]
Что-то не так с запросами `checkForNotifications` и `checkTableIsChanged`, если метод `checkForNotifications` выполняется в среднем около 20 сек, то последний занимает в среднем около 1 мин.
При использовании totum одновременно несколькими пользователями да еще в нескольких вкладках количество запросов к бд значительно увеличивается и система прилично тупит.

При отключении этих методов в коде система вновь становится жизнеспособной.

![Selection_355](https://user-images.githubusercontent.com/2429298/131582568-b3bdb386-2bf1-4aac-8c04-c8c4e9021c0b.png)

**Comment by poluninatm** [comment]
Добрый день, это стандартное поведение и не является зависом - метод checkForNotifications выполняется минуту не потому что завис - он каждые (количество секунд установленных у вас в настройках нотификаций) опрашивает базу на предмет новых нотификаций для пользователя. После минуты он обрубает соединение, чтобы не вызывать проблем с nginx/apache.

В тот момент, когда вкладка у пользователя становится неактивной, эти запросы к серверу обрубаются и восстанавливаются только после активизации вкладки. Если этого не происходит, прошу сообщить ваш броузер, его версию и вашу версию Тотум.

Если вы развернули систему на локальном компьютере на тестовом сервере php через php -S - тестовый сервер php является однопоточным и не может обрабатывать два запроса одновременно. Для этой ситуации прошу в качестве тестового хоста использовать localhost:8080 - на нем отключается корректный ответ этих функций, вы не сможете посмотреть их работу, но помимо этого все будет работать адекватно.

В различных вариантах эксплуатации со многими пользователями мы не еще сталкивались с проблемами в этой функциональности. Если я не смогла вам помочь, опишите проблему подробнее, в том числе окружение: броузер (с версией), версия Тотум, количество  одновременных пользователей, с которыми возникает проблема, текущий объем базы...

**Comment by poluninatm** [comment]
https://docs.totum.online/ubuntu#pm - возможно, не хватает процессов php-fpm?

Если хотите посмотреть на запросы к БД - можно временно переопределить в Conf.php конструктор и в myLogs будут писаться sql-запросы со временем выполнения - никакого уборщика/архиватора логов нет - это чисто для разработки/отладки: 
  public function __construct($env = self::ENV_LEVELS["production"])
    {
       parent::__construct($env= self::ENV_LEVELS["development"]);
    }

**Comment by mervick** [comment]
Спасибо.
Разобрался, в одной из таблиц селект пересчитывался для каждой строки из-за чего возникали данные подвисания.
