### ISSUE TITLE
Разная трактовка знака равно для selectList where

### ISSUE THREAD

**Issue by mervick** [totumonline/totum-mit#209]
При выборке функцией `selectList` при использовании параметра `where` знаки `=` и `==` трактуется по разному и выдают разный результат, что вовсе не очевидно.
Возможно это связано, с версией php, но на вашем тестовом сервере все работает вроде как нужно, у меня же такие одинаковые по смыслу выражения выдают разные результаты:
```
= : listSum(list: $list)
list: selectList(table: 'order_payments'; field: 'paid_usd'; where: 'order_number' = $#nci)
```
![Selection_398](https://user-images.githubusercontent.com/2429298/132541224-188e58c9-9de7-4190-b768-213e2e63a77d.png)

```
= : listSum(list: $list)
list: selectList(table: 'order_payments'; field: 'paid_usd'; where: 'order_number' == $#nci)
```
![Selection_399](https://user-images.githubusercontent.com/2429298/132541260-78164dd2-db38-4f4c-8125-7f6c3f5ec7bc.png)

```
PHP 7.4.3 (cli) (built: Jul  5 2021 15:13:35) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies
```

**Comment by ttm-alexeypolunin** [comment]
Одинарное равно `=` — это вхождение:

+ `1`= `1`
+ `1` = `[1,2,3]`
+ `1`= `[1]`

Двойное равно `==` — это полное соответствие:

+ `1`= =`1`
+ `1` == `"1"`

Но возможно у нас ошибка в сравнениях, которую мы не видим.

1. Скажите какой тип поля используется для `order_number`

2. Включите отладку по кодам и посмотрите в чем разница выбираемых списков:

2.1 Надо включить https://docs.totum.online/debugging#sx-enabling-debugging

2.2 Обновляем страницу и в контекстн панели по правой кнопке `Ic`

Нам нужно понять, какое значение `order_number` попадает в интервал лишним или не попадает если там есть отрицательные суммы в `paid_usd`.

**Comment by mervick** [comment]
Извините за долгий фидбек.

Итак, тип поля для `order_number` - селект, в качестве ключей используется данные из таблицы где `order_number` - строка.

при `=`
```
= : listSum(list: $list)
list: selectList(table: 'order_payments'; field: 'paid_usd'; where: 'order_number' = $#nci)
```
считает только 1 запись

![Selection_405](https://user-images.githubusercontent.com/2429298/133788487-2f0cb217-34af-4711-9fd5-cf627b95565e.png)

при `==` 
```
= : listSum(list: $list)
list: selectList(table: 'order_payments'; field: 'paid_usd'; where: 'order_number' == $#nci)
```
![Selection_406](https://user-images.githubusercontent.com/2429298/133788635-d4fb3f9c-fcc4-4c13-b578-79d0c0eec0ba.png)

**Comment by ttm-alexeypolunin** [comment]
Спасибо, что моричитесь.

1. Правильно ли мы понимаем, что номера циклов записываются в промежуточной таблице в текстовое поле, а в `order_number` используется `bfield` по этому строковому полю?

2. Хотя бы одна из этих выборок верная?

3. Можете сделать рядом поле тип Данные и в `код` выполнить:

```
=: rowCreate(field: "single" = $single; field: "double" = $double)

single: selectRowList(table: 'order_payments'; field: 'order_number'; field: 'paid_usd'; where: 'order_number' = $#nci)
double: selectRowList(table: 'order_payments'; field: 'order_number'; field: 'paid_usd'; where: 'order_number' == $#nci)
```

и прислать нам получившийся json

**Comment by ttm-alexeypolunin** [comment]
Самый хороший вариант, если вы в Телеграм мне напишете @alexeypolunin и дадите нам admin-доступ к вашему Тотум, что бы мы глазами глянули
