### ISSUE TITLE
comment field error

### ISSUE THREAD

**Issue by criszalo1997** [totumonline/totum-mit#222]
hello devs I have found this error when creating a comment type field in the footer of a table in cycle type, if you could help me solve this problem I would appreciate it in the same way thanks for this great tool
`<br />
<b>Warning</b>:  foreach() argument must be of type array|object, string given in <b>/home/totum/totum-mit/totum/fieldTypes/Comments.php</b> on line <b>163</b><br />
{"value":""}`

![image](https://user-images.githubusercontent.com/29022806/163695323-7d3925dd-637a-4381-972c-74f5d7fcbeb5.png)

**Comment by ttm-alexeypolunin** [comment]
accept, we will look at it tomorrow

are you using docker or git-install?

**Comment by criszalo1997** [comment]
use git for installation

**Comment by ttm-alexeypolunin** [comment]
We can see that the error is caused by a string arriving in the field instead of the array we need.

We put a patch there now and will update the repo in the evening. How to update — https://docs.totum.online/update

But we can't repeat what preceded it. Maybe there was a field of another type and then the type was changed to comments? Or something special was added to the comment?

If you delete the field, create a new one immediately with the type of comment and open it for editing?

**Comment by criszalo1997** [comment]
Hello, I'm telling you that there was another field or I didn't modify the field to be of the comment type. When creating that field from scratch, the error I mentioned appeared, but it seems that your patch to the project solved my problem and everything works fine.
Thank you very much for taking your time. Greetings.

![image](https://user-images.githubusercontent.com/29022806/163869032-6dd1ab5c-9a15-406c-a701-749207e56a6a.png)

**Comment by ttm-alexeypolunin** [comment]
Okay. I think you will find other problems in our craft :) Tell us about it if you have time.

**Comment by criszalo1997** [comment]
Error printing a field of type comment:

Hello, how are you? I found an error in the same field of type comment when I perform the action of printing this error appears

`<br />
<b>Warning</b>:  Undefined array key "column" in <b>/home/totum/totum-mit/totum/moduls/Table/ReadTableActions.php</b> on line <b>1012</b><br />
{"interfaceDatas":[["print",{"styles":"@import url(\"https:\/\/fonts.googleapis.com\/css?family=Open+Sans:400,600|Roboto:400,400i,700,700i,500|Roboto+Mono:400,700&amp;subset=cyrillic\");\nbody {font-family: 'Roboto', sans-serif; }\ntable {border-spacing: 0; border-collapse: collapse; margin-top: 20px; table-layout: fixed; width: 100%}\ntable tr td {border: 1px solid gray; padding: 3px; overflow: hidden; text-overflow: ellipsis}\ntable tr td.title {font-weight: bold; vertical-align: top}\ntable tr td.f-checkbox {text-align: center}\ntable tr td span{text-overflow: ellipsis; width: 100%; overflow: hidden; display: block;}\nspan.deleted{text-decoration: line-through}\n.table-print_templates table tr td.n-name {font-style: italic}","body":"<div style=\"position: absolute; right: 0px; top: 0px;\">\n  <img src=\"\/fls\/297_main_img.png\" style=\"width: 40px;\"\/>\n<\/div>\n<div class=\"table-venta\"><h1>VENTA #10<\/h1><table style=\"width: 250px;\"><thead><tr><td style=\"width: 250px;\" class=\"title\">Referencia<\/td><td style=\"width: 250px;\" class=\"title\">Cliente<\/td><td style=\"width: 250px;\" class=\"title\">Fecha de Emisión<\/td><td style=\"width: 250px;\" class=\"title\">Fecha de Cierre<\/td><td style=\"width: 250px;\" class=\"title\">N° Serie<\/td><\/tr><\/thead><tbody><tr><td class=\"f-string n-h_referencia\"><span>venta de viveres<\/span><\/td><td class=\"f-select n-h_cliente\"><span><div><span>LAB ZUNA<\/span><\/div><\/span><\/td><td class=\"f-date n-h_fecha_emision\"><span>04\/22\/2022<\/span><\/td><td class=\"f-date n-fecha_cierre\"><span>05\/05\/2022<\/span><\/td><td class=\"f-string n-h_codigo\"><span>S33-SDDRF<\/span><\/td><\/tr><\/tbody><\/table><table style=\"width: 500px;\"><thead><tr><td style=\"width: 250px;\" class=\"title\">Impuesto<\/td><td style=\"width: 250px;\" class=\"title\">Estado<\/td><\/tr><\/thead><tbody><tr><td class=\"f-select n-h_impuesto\"><span><div><span>IVA<\/span><\/div><\/span><\/td><td class=\"f-select n-h_estado\"><span><div><span>-<\/span><\/div><\/span><\/td><\/tr><\/tbody><\/table><table style=\"width: 1050px;\"><thead><tr><td style=\"width: 200px;\" class=\"title\">Productos<\/td><td style=\"width: 100px;\" class=\"title\">Cantidad<\/td><td style=\"width: 100px;\" class=\"title\">Unidad<\/td><td style=\"width: 100px;\" class=\"title\">Stock<\/td><td style=\"width: 100px;\" class=\"title\">incoterms<\/td><td style=\"width: 150px;\" class=\"title\">Precio Incoterms<\/td><td style=\"width: 150px;\" class=\"title\">Precio Unitario<\/td><td style=\"width: 150px;\" class=\"title\">Precio Total<\/td><\/tr><\/thead><tbody><tr><tr><td class=\"f-select n-productos\"><span><div><span>Router<\/span><\/div><\/span><\/td><td class=\"f-number n-cantidad\"><span>8<\/span><\/td><td class=\"f-string n-unidad\"><span>mts<\/span><\/td><td class=\"f-number n-stock\"><span>0<\/span><\/td><td class=\"f-string n-incoterms\"><span>TC<\/span><\/td><td class=\"f-number n-precio_incoterms\"><span>200,00<\/span><\/td><td class=\"f-number n-precio_unitario\"><span>4 285,00<\/span><\/td><td class=\"f-number n-precio_total\"><span>34 480,00<\/span><\/td><\/tr><tr><td class=\"f-select n-productos\"><span><div><span>Computadoras<\/span><\/div><\/span><\/td><td class=\"f-number n-cantidad\"><span>10<\/span><\/td><td class=\"f-string n-unidad\"><span>pza<\/span><\/td><td class=\"f-number n-stock\"><span>0<\/span><\/td><td class=\"f-string n-incoterms\"><span>TC<\/span><\/td><td class=\"f-number n-precio_incoterms\"><span>150,00<\/span><\/td><td class=\"f-number n-precio_unitario\"><span>4 875,68<\/span><\/td><td class=\"f-number n-precio_total\"><span>48 906,80<\/span><\/td><\/tr><tr><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td class=\"title\">Impuestos Unitario<\/td><td class=\"title\">Total Impuestos<\/td><\/tr><tr><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td class=\"f-number n-f_impuestos_unitario\">1465.71<\/td><td class=\"f-number n-f_total_impuestos\">13341.8880000000<\/td><\/tr><tr><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td class=\"title\">Total Unitario<\/td><td class=\"title\">Total<\/td><\/tr><tr><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td class=\"f-number n-f_total_unitario\">10 626,39<\/td><td class=\"f-number n-f_total_total\">84 852,51<\/td><\/tr><\/tr><\/tbody><\/table><table style=\"width: 500px;\"><thead><tr><td style=\"width: 500px;\" class=\"title\">Nota<\/td><\/tr><\/thead><tbody><tr><td class=\"f-comments n-f_nota\"><span><div><span>18.04<\/span><span>Administrator<\/span><span>otro comment<\/span><\/div><\/span><\/td><\/tr><\/tbody><\/table><\/div>","refresh":false,"elseData":[]}]]}`

comment type field
![image](https://user-images.githubusercontent.com/29022806/164792489-d2913821-412b-459f-9ab2-95e28f582f06.png)

**Comment by criszalo1997** [comment]
> Error printing a field of type comment:
> 
> Hello, how are you? I found an error in the same field of type comment when I perform the action of printing this error appears
> 
> `<br /> <b>Warning</b>: Undefined array key "column" in <b>/home/totum/totum-mit/totum/moduls/Table/ReadTableActions.php</b> on line <b>1012</b><br /> {"interfaceDatas":[["print",{"styles":"@import url(\"https:\/\/fonts.googleapis.com\/css?family=Open+Sans:400,600|Roboto:400,400i,700,700i,500|Roboto+Mono:400,700&amp;subset=cyrillic\");\nbody {font-family: 'Roboto', sans-serif; }\ntable {border-spacing: 0; border-collapse: collapse; margin-top: 20px; table-layout: fixed; width: 100%}\ntable tr td {border: 1px solid gray; padding: 3px; overflow: hidden; text-overflow: ellipsis}\ntable tr td.title {font-weight: bold; vertical-align: top}\ntable tr td.f-checkbox {text-align: center}\ntable tr td span{text-overflow: ellipsis; width: 100%; overflow: hidden; display: block;}\nspan.deleted{text-decoration: line-through}\n.table-print_templates table tr td.n-name {font-style: italic}","body":"<div style=\"position: absolute; right: 0px; top: 0px;\">\n <img src=\"\/fls\/297_main_img.png\" style=\"width: 40px;\"\/>\n<\/div>\n<div class=\"table-venta\"><h1>VENTA #10<\/h1><table style=\"width: 250px;\"><thead><tr><td style=\"width: 250px;\" class=\"title\">Referencia<\/td><td style=\"width: 250px;\" class=\"title\">Cliente<\/td><td style=\"width: 250px;\" class=\"title\">Fecha de Emisión<\/td><td style=\"width: 250px;\" class=\"title\">Fecha de Cierre<\/td><td style=\"width: 250px;\" class=\"title\">N° Serie<\/td><\/tr><\/thead><tbody><tr><td class=\"f-string n-h_referencia\"><span>venta de viveres<\/span><\/td><td class=\"f-select n-h_cliente\"><span><div><span>LAB ZUNA<\/span><\/div><\/span><\/td><td class=\"f-date n-h_fecha_emision\"><span>04\/22\/2022<\/span><\/td><td class=\"f-date n-fecha_cierre\"><span>05\/05\/2022<\/span><\/td><td class=\"f-string n-h_codigo\"><span>S33-SDDRF<\/span><\/td><\/tr><\/tbody><\/table><table style=\"width: 500px;\"><thead><tr><td style=\"width: 250px;\" class=\"title\">Impuesto<\/td><td style=\"width: 250px;\" class=\"title\">Estado<\/td><\/tr><\/thead><tbody><tr><td class=\"f-select n-h_impuesto\"><span><div><span>IVA<\/span><\/div><\/span><\/td><td class=\"f-select n-h_estado\"><span><div><span>-<\/span><\/div><\/span><\/td><\/tr><\/tbody><\/table><table style=\"width: 1050px;\"><thead><tr><td style=\"width: 200px;\" class=\"title\">Productos<\/td><td style=\"width: 100px;\" class=\"title\">Cantidad<\/td><td style=\"width: 100px;\" class=\"title\">Unidad<\/td><td style=\"width: 100px;\" class=\"title\">Stock<\/td><td style=\"width: 100px;\" class=\"title\">incoterms<\/td><td style=\"width: 150px;\" class=\"title\">Precio Incoterms<\/td><td style=\"width: 150px;\" class=\"title\">Precio Unitario<\/td><td style=\"width: 150px;\" class=\"title\">Precio Total<\/td><\/tr><\/thead><tbody><tr><tr><td class=\"f-select n-productos\"><span><div><span>Router<\/span><\/div><\/span><\/td><td class=\"f-number n-cantidad\"><span>8<\/span><\/td><td class=\"f-string n-unidad\"><span>mts<\/span><\/td><td class=\"f-number n-stock\"><span>0<\/span><\/td><td class=\"f-string n-incoterms\"><span>TC<\/span><\/td><td class=\"f-number n-precio_incoterms\"><span>200,00<\/span><\/td><td class=\"f-number n-precio_unitario\"><span>4 285,00<\/span><\/td><td class=\"f-number n-precio_total\"><span>34 480,00<\/span><\/td><\/tr><tr><td class=\"f-select n-productos\"><span><div><span>Computadoras<\/span><\/div><\/span><\/td><td class=\"f-number n-cantidad\"><span>10<\/span><\/td><td class=\"f-string n-unidad\"><span>pza<\/span><\/td><td class=\"f-number n-stock\"><span>0<\/span><\/td><td class=\"f-string n-incoterms\"><span>TC<\/span><\/td><td class=\"f-number n-precio_incoterms\"><span>150,00<\/span><\/td><td class=\"f-number n-precio_unitario\"><span>4 875,68<\/span><\/td><td class=\"f-number n-precio_total\"><span>48 906,80<\/span><\/td><\/tr><tr><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td class=\"title\">Impuestos Unitario<\/td><td class=\"title\">Total Impuestos<\/td><\/tr><tr><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td class=\"f-number n-f_impuestos_unitario\">1465.71<\/td><td class=\"f-number n-f_total_impuestos\">13341.8880000000<\/td><\/tr><tr><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td class=\"title\">Total Unitario<\/td><td class=\"title\">Total<\/td><\/tr><tr><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td><\/td><td class=\"f-number n-f_total_unitario\">10 626,39<\/td><td class=\"f-number n-f_total_total\">84 852,51<\/td><\/tr><\/tr><\/tbody><\/table><table style=\"width: 500px;\"><thead><tr><td style=\"width: 500px;\" class=\"title\">Nota<\/td><\/tr><\/thead><tbody><tr><td class=\"f-comments n-f_nota\"><span><div><span>18.04<\/span><span>Administrator<\/span><span>otro comment<\/span><\/div><\/span><\/td><\/tr><\/tbody><\/table><\/div>","refresh":false,"elseData":[]}]]}`
> 
> comment type field ![image](https://user-images.githubusercontent.com/29022806/164792489-d2913821-412b-459f-9ab2-95e28f582f06.png)

help please

**Comment by ttm-alexeypolunin** [comment]
We will fix this on Monday.

**Comment by ttm-alexeypolunin** [comment]
fix in 2.3.39

**Comment by criszalo1997** [comment]
thanks
