### ISSUE TITLE
Totem JS code is almost unreadable

### ISSUE THREAD

**Issue by carbonrider** [totumonline/totum-mit#238]
While glancing through the totem code, I was quite interested in the frontend part. But to my disappointment most of the code is minified and hence quite unreadable.

e.g.

- http/js/forms.js
- http/js/functions.js
- http/js/main.js

Also the JS inside lib folder is minified as well.

**Comment by poluninatm** [comment]
Hello, the front is developed in the repository https://github.com/totumonline/totum-front

functions.js contains a description of functions for autocomplete and code highlighting. You can take the value of App.functions and put it in json viewer
