### ISSUE TITLE
"Не беспокойтей об одновременном доступе" в README_RU.md

### ISSUE THREAD

**Issue by veretennikovalexey** [totumonline/totum-mit#251]
https://github.com/totumonline/totum-mit/blob/master/README_RU.md

Не беспокойтей об одновременном доступе — транзакции атоматические

Небольшие ошибки в русском ридми

**Comment by ttm-alexeypolunin** [comment]
Я удивлен, что его кто-то прочитал :)

**Comment by veretennikovalexey** [comment]
> одновременном

а ещё буква в слове "атоматические"

я бы сам исправил, но я не умею делать пул реквесты

это надо форкать, вносить изменения ? или как
