### ISSUE TITLE
Уязвимость linkToPanel

### ISSUE THREAD

**Issue by ttm-alexeypolunin** [totumonline/totum-mit#75]
Сейчас, после того как панель открыта машина считает, что она трастовая и можно подменить id строки и отправить данные в ту часть таблицы, которая может быть заблокирована для роли.

**Comment by poluninatm** [comment]
При запросе на изменение/удаление строки из веб/апи включена проверка на расположение строки в зоне действующих нередактируемых фильтров для роли+интерфейса. Если строка вне зоны фильтров - выдается ошибка

22590aff58d56f43db00fb394038a563d81e7c4b
