### ISSUE TITLE
Сделать функцию форматирования таблицы  setTableTitle и setTableColumnsTitle

### ISSUE THREAD

**Issue by ttm-alexeypolunin** [totumonline/totum-mit#95]

**Comment by poluninatm** [comment]
Добавлены параметры в функцию setTableFormat - tabletitle, rowstitle, fieldtitle

**Comment by poluninatm** [comment]
Добавлена обработка параметра пола sectionTitle для полей не колоночных полей, у которых выставлен параметр tableBreakBefore в true
